config/routes.rb
MultipleUp::Application.routes.draw do
  resources :post_attachments

  resources :posts

  root :to => 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  attr_accessible :description, :name, :post_attachments_attributes

  has_many :post_attachments

  accepts_nested_attributes_for :post_attachments

end

app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
  
  belongs_to :post

  attr_accessible :file, :post_id

  mount_uploader :file, ArchivoUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @post_attachments }
    end
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
    @post_attachment = PostAttachment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post_attachment }
    end
  end

  # GET /post_attachments/new
  # GET /post_attachments/new.json
  def new
    @post_attachment = PostAttachment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post_attachment }
    end
  end

  # GET /post_attachments/1/edit
  def edit
    @post_attachment = PostAttachment.find(params[:id])
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(params[:post_attachment])

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully created.' }
        format.json { render json: @post_attachment, status: :created, location: @post_attachment }
      else
        format.html { render action: "new" }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /post_attachments/1
  # PUT /post_attachments/1.json
  def update
    @post_attachment = PostAttachment.find(params[:id])

    respond_to do |format|
      if @post_attachment.update_attributes(params[:post_attachment])
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment = PostAttachment.find(params[:id])
    @post_attachment.destroy

    respond_to do |format|
      format.html { redirect_to post_attachments_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    #@post_attachments = @post.post_attachments.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new
    @post_attachment = @post.post_attachments.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        params[:post_attachments]['file'].each do |a|
          @post_attachment = @post.post_attachments.create!(:file => a, :post_id => @post.id)
        end
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MultipleUp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/post_attachments/_form.html.erb
<%= form_for(@post_attachment) do |f| %>
  <% if @post_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_attachment.errors.count, "error") %> prohibited this post_attachment from being saved:</h2>

      <ul>
      <% @post_attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %><br />
    <%= f.text_field :file %>
  </div>
  <div class="field">
    <%= f.label :post %><br />
    <%= f.text_field :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_attachments/edit.html.erb
<h1>Editing post_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/index.html.erb
<h1>Listing post_attachments</h1>

<table>
  <tr>
    <th>File</th>
    <th>Post</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @post_attachments.each do |post_attachment| %>
  <tr>
    <td><%= post_attachment.file %></td>
    <td><%= post_attachment.post %></td>
    <td><%= link_to 'Show', post_attachment %></td>
    <td><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></td>
    <td><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post attachment', new_post_attachment_path %>

app/views/post_attachments/new.html.erb
<h1>New post_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>File:</b>
  <%= @post_attachment.file %>
</p>

<p>
  <b>Post:</b>
  <%= @post_attachment.post %>
</p>


<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
<%= link_to 'Back', post_attachments_path %>

app/views/posts/_form.html.erb
<%= form_for(@post, :html => { :multipart => true }) do |f| %>
   <div class="field">
     <%= f.label :name %><br>
     <%= f.text_field :name %>
   </div>

   <%= f.fields_for :post_attachments do |p| %>
     <div class="field">
       <%= p.label :file %><br>
       <%= p.file_field :file, :multiple => true, name: "post_attachments[file][]" %>
     </div>
   <% end %>

   <div class="actions">
     <%= f.submit %>
   </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.name %></td>
    <td><%= post.description %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.name %>
</p>

<% @post.post_attachments.each do |p| %>
  <%= link_to "File", p.file_url %>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>